### ISSUE TITLE
Label naming confusing

### ISSUE THREAD

**Issue by XDjackieXD** [SpaceTeam/STS1_EPS#16]
For example the Label "Bat+" and "Bat+_UCI" in the Solar Cell Connectors sheet are very confusing as Bat+ is the input from the UCI. Not Bat+_UCI.

Please define a naming schema and then stick to it.

**Comment by asmolyanyuk** [comment]
On the board 1 there is a mismatch between the panel connector labels and the labels for their pin-outs . For example, Panel Z- has pin-outs marked as Panel_X+.

**Comment by McBrez** [comment]
Original issue is fixed in  a812255. Created issue #28 for @asmolyanyuk  's comment.
