### ISSUE TITLE
TPS259472ARPW for UART?

### ISSUE THREAD

**Issue by XDjackieXD** [SpaceTeam/STS1_EPS#17]
Has someone tested that it works with an UART connection? The stray capacitance and turn on delay is extremely high so I suspect that it wont work (this UART has to work up to 115200 baud).

The usual solution for UART protection is a Zener/TVS Diode and a 100Ohm series resistor.

**Comment by McBrez** [comment]
Removed TSP259472ARPW. Added TVS diodes to the UART lines. Didn't place 100Ohm resistor, as there is already on the COBC.
3b45b82
