### ISSUE TITLE
Board2 TPS2420RSAT max IO port input voltage

### ISSUE THREAD

**Issue by XDjackieXD** [SpaceTeam/STS1_EPS#27]
Max input voltage of any logic input of the TPS2420RSAT is 5V.
The gate that inputs into it is supplied by V_LOGIC which - as far as I can tell - can be significantly above 5V.

**Comment by McBrez** [comment]
Fixed in e0c62bc.

**Comment by McBrez** [comment]
Added a linear regulator in b77aafa.
